sudo: required
# we need a copy of docker ready to go
services:
  - docker 

before_install:
  - docker build -t vaish0299/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vaish0299/docker-react npm run test

